FROM ubuntu:20.04

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -qqy \
    python3 \
    python3-pip \
    git-all wget \
    default-jre

RUN wget https://faculty.washington.edu/browning/beagle/beagle.01Mar24.d36.jar -O beagle.jar




